import {
  attribute,
  autoGeneratedHashKey,
  table,
} from "@aws/dynamodb-data-mapper-annotations";

@table("contract_table")
export class Contract {
  @autoGeneratedHashKey()
  id: string;

  /**
   * Contract's User ID
   */
  @attribute({ type: "String" })
  userId?: string;

  /**
   * Contract Name
   */
  @attribute({ type: "String" })
  name?: string;

  /**
   * Contract's template ID
   */
  @attribute({ type: "String" })
  templateId?: string;

  /**
   * Contract's creation date
   */
  @attribute({
    type: "Date",
    defaultProvider: () => new Date(),
  })
  createdAt?: Date;
}
